[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/:path*"
  to = "https://backend-swft.onrender.com/:path"
  status = 200
  force = true